service: aws-node-express-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  httpApi:
    cors: true

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
